# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: elidebi

provider:
  name: aws
  runtime: nodejs8.10
  stage: staging
  region: eu-central-1
  profile: elidebi
  apiKeys:
    - testing
  usagePlan:
    quota:
      limit: 10
      offset: 0
      period: DAY
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  create-event:
    handler: events.create
    environment: 
      RDS_ENDPOINT: ${ssm:rds_endpoint}
      RDS_ADMIN: ${ssm:rds_admin}
      RDS_PASSWORD: ${ssm:rds_password}
    vpc: 
      securityGroupIds:
        - sg-e3aea48e 
      subnetIds:
        - subnet-7b360110
        - subnet-cd3a4580
  lottery-create:
    handler: lottery.create
    environment: 
      RDS_ENDPOINT: ${ssm:rds_endpoint}
      RDS_ADMIN: ${ssm:rds_admin}
      RDS_PASSWORD: ${ssm:rds_password}
    vpc: 
      securityGroupIds:
        - sg-e3aea48e 
      subnetIds:
        - subnet-7b360110
        - subnet-cd3a4580
  lottery-get-mine:
    handler: lottery.getMine
    environment: 
      RDS_ENDPOINT: ${ssm:rds_endpoint}
      RDS_ADMIN: ${ssm:rds_admin}
      RDS_PASSWORD: ${ssm:rds_password}
    vpc: 
      securityGroupIds:
        - sg-e3aea48e 
      subnetIds:
        - subnet-7b360110
        - subnet-cd3a4580
    events:
      - http:
          path: lottery/mine
          method: get
          private: true
  members-list:
    handler: members.list
    environment: 
      RDS_ENDPOINT: ${ssm:rds_endpoint}
      RDS_ADMIN: ${ssm:rds_admin}
      RDS_PASSWORD: ${ssm:rds_password}
    vpc: 
      securityGroupIds:
        - sg-e3aea48e 
      subnetIds:
        - subnet-7b360110
        - subnet-cd3a4580
    events:
      - http:
          path: members
          method: get
          private: true

      